global class TicketTransferFields {

    @InvocableVariable
    global String email;

    @InvocableVariable
    global Long groupId;

    @InvocableVariable
    global Integer priority;

    @InvocableVariable
    global Integer source;

    @InvocableVariable
    global Integer status;

    @InvocableVariable
    global String subject;

    @InvocableVariable
    global String type;

    @InvocableVariable
    global String serviceTeam;

    @InvocableVariable
    global String tags;

    @InvocableVariable
    global String description;

}